name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Sync files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/
          # On essaie avec ./ pour être relatif à la racine de ton compte FTP
          server-dir: ./public_html/
          # --- OPTIONS ANTI-TIMEOUT ET SÉCURITÉ ---
          protocol: ftp
          port: 21
          # Obligatoire pour passer le pare-feu de GitHub vers Hostinger
          passive: true
          # Évite que l'action reste bloquée si le serveur met du temps à répondre
          timeout: 60000